name: Push to Target Repository via SSH

on:
  push:
    branches:
      - main

jobs:
  push_to_target_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: hplc

      - name: Set target repository information
        run: |
          echo "TARGET_REPO_URL=https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO_USERNAME }}/${{ secrets.TARGET_REPO_NAME }}.git" >> $GITHUB_ENV

      - name: Push to target repository
        run: |
          git remote add target ${{ env.TARGET_REPO_URL }}
          git remote -v
          git push target hplc:hplc --force