name: Push to Target Repository via SSH

on:
  push:
    branches:
      - main

jobs:
  push_to_target_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          ref: hplc

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Add target remote
        run: |
          git remote add target https://${{ secrets.TARGET_REPO_TOKEN }}@github.com/${{ secrets.TARGET_REPO_USERNAME }}/${{ secrets.TARGET_REPO_USERNAME }}.github.io.git
          git remote -v
          
      - name: Push to target repository
        run: |
          git push target hplc:hplc --force